<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AskApollo.Application\AskApollo.Application.csproj" />
    <ProjectReference Include="..\AskApollo.Domain\AskApollo.Domain.csproj" />
    <ProjectReference Include="..\AskApollo.Shared\AskApollo.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
